apiVersion: "nuclio.io/v1"
kind: NuclioFunction
metadata:
  name: local_job-test
  namespace: nuclio
spec:
  runtime: python:3.10
  handler: job:handler
  triggers:
    myHttpTrigger:
      kind: job
      attributes:
        dataFile: "/tmp/job_input.txt"
      maxWorkers: 1