apiVersion: "nuclio.io/v1"
kind: NuclioFunction
metadata:
  name: local_job-test
  namespace: nuclio
spec:
  runtime: python:3.10
  handler: job_file:handler
  triggers:
    myJobTrigger:
      kind: job
      attributes:
      maxWorkers: 1