apiVersion: "nuclio.io/v1"
kind: NuclioFunction
metadata:
  name: local_job-test
  namespace: nuclio
spec:
  runtime: python:3.10
  handler: job_event:handler
  triggers:
    myJobTrigger:
      kind: job
      attributes:
        event:
          body: "{\"text\": \"Test text. Job is done.\"}"
      maxWorkers: 1