# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0
FROM python:3.12-slim

LABEL org.opencontainers.image.source=https://github.com/scc-digitalhub/digitalhub-serverless

ARG ver_sdk=0.14.0b4
ARG ver_python=0.14.0b4
ARG ver_container=0.14.0b2
ARG ver_modelserve=0.14.0b4
ARG ver_dbt=0.14.0b1
ARG ver_kfp=0.14.0b2
ARG ver_hera=0.14.0b4
ARG ver_flower=0.14.0b3

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    libpq-dev \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

RUN python -m pip install "digitalhub[full]==${ver_sdk}" \
                          "digitalhub-runtime-python==${ver_python}" \
                          "digitalhub-runtime-container==${ver_container}"  \
                          "digitalhub-runtime-modelserve==${ver_modelserve}" \
                          "digitalhub-runtime-dbt==${ver_dbt}" \
                          "digitalhub-runtime-kfp==${ver_kfp}" \
                          "digitalhub-runtime-flower==${ver_flower}" \
                          "digitalhub-runtime-hera==${ver_hera}" \
                          "msgpack" \
                          "nuclio-sdk"

RUN useradd -r -m -u 8877 nonroot
USER 8877

WORKDIR /shared
