# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

# --- Build processor binary ---
FROM  golang:1.25 AS go-builder

WORKDIR /src/digitalhub-serverless

# Cache go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy sources
COPY . ./
# Compile processor
RUN set -euo pipefail; \
    CGO_ENABLED=0 \
      go build \
        -ldflags="-s -w \
          -X github.com/v3io/version-go.gitCommit=unknown \
          -X github.com/v3io/version-go.label=latest" \
        -o /out/processor \
        cmd/processor/main.go


FROM scratch

# Go artifacts
COPY --from=go-builder /out/processor /layer/bin/processor
