# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0
FROM python:3.11-slim

LABEL org.opencontainers.image.source=https://github.com/scc-digitalhub/digitalhub-serverless

ARG ver_sdk=0.14.12
ARG ver_python=0.14.2


RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    libpq-dev \
    default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -r -m -u 8877 nonroot
USER 8877

RUN python -m pip install "digitalhub[full]==${ver_sdk}" \
                          "digitalhub-runtime-python==${ver_python}" \
                          "msgpack" \
                          "nuclio-sdk"

ENV PATH="/home/nonroot/.local/bin:$PATH"
ENV PYTHONPATH="/home/nonroot/.local/lib/python3.11/site-packages"

WORKDIR /shared
